name: SDK Version
on:
  pull_request: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  compatibility:
    name: Check for empty or re-used version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout PR source code
        uses: actions/checkout@v3
      - name: Extract version
        run: test `cat infra/jsonclient/bearer.go | grep -o 'bearerToken := h.Get("[^"]*' | grep -o '[^"]*$'` = ""
