name: SDK Version Check
on:
  pull_request: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  compatibility:
    name: Check for empty or re-used SDK version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout PR source code
        uses: actions/checkout@v3
      - name: Verify sdkVersion is not empty and is not existing tag
        run: TOKEN=`cat infra/jsonclient/bearer.go | grep -o 'bearerToken := h.Get("[^"]*' | grep -o '[^"]*$'`; test -n $TOKEN && test "`git tag -l | grep $TOKEN`" = "" && echo $TOKEN && git describe --tags
